### ISSUE TITLE
Error in library(sounDMR) : there is no package called ‘sounDMR'

### ISSUE THREAD

**Issue by BeatrizFaustino** [SoundAg/sounDMR#53]
When installing SounDMR, when running the library this error appears. What could be happening? Below are the messages that appear:
The downloaded binary packages are in
C:\Users\alang\AppData\Local\Temp\RtmpoxOiuz\downloaded_packages
── R CMD build ──────────────────────────────────── ───────── ────────────────────────
✔ checking for file 'C:\Users\alang\AppData\Local\Temp\RtmpoxOiuz\remotes3ca038de3832\SoundAg-sounDMR-dbf6e22/DESCRIPTION' (509ms)
─ preparing 'soundDMR':
✔ checking DESCRIPTION meta-information ...
─ checking for LF line-endings in source and make files and shell scripts
─ checking for empty or unneeded directories
─ building 'sounDMR_2.2.2.tar.gz'
   
*installing *source* package 'sounDMR' ...
** using staged installation
**R
**inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'data.table::melt' by 'reshape2::melt' when loading 'sounDMR'
Warning: replacing previous import 'data.table::dcast' by 'reshape2::dcast' when loading 'sounDMR'
Warning: replacing previous import 'changepoint::logLik' by 'stats::logLik' when loading 'sounDMR'
Warning: replacing previous import 'changepoint::coef' by 'stats::coef' when loading 'sounDMR'
** help
***installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Warning: replacing previous import 'data.table::melt' by 'reshape2::melt' when loading 'sounDMR'
Warning: replacing previous import 'data.table::dcast' by 'reshape2::dcast' when loading 'sounDMR'
Warning: replacing previous import 'changepoint::logLik' by 'stats::logLik' when loading 'sounDMR'
Warning: replacing previous import 'changepoint::coef' by 'stats::coef' when loading 'sounDMR'
Error: package or namespace load failed for 'sounDMR' in namespaceExport(ns, exports):
  undefined exports: plot_changepoints
Error: loading failed
Execution stopped
ERROR: loading failed
* removing 'C:/Program Files/R/R-4.3.2/library/sounDMR'
Warning message:
In i.p(...) :
   installation of package ‘C:/Users/alang/AppData/Local/Temp/RtmpoxOiuz/file3ca06c901a53/sounDMR_2.2.2.tar.gz’ had non-zero exit status
> library(soundDMR)
Error in library(sounDMR) : there is no package called ‘sounDMR’

**Comment by kwglam** [comment]
Hi,
When installing soundDMR, I came across with the following error:

installing to /home/R/x86_64-redhat-linux-gnu-library/4.3/00LOCK-xml2/00new/xml2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : read_xml.Rd:58: unable to load shared object '/home/R/x86_64-redhat-linux-gnu-library/4.3/00LOCK-xml2/00new/xml2/libs/xml2.so':
  libiconv.so.2: cannot open shared object file: No such file or directory
ERROR: installing Rd objects failed for package ‘xml2’
* removing ‘/home/R/x86_64-redhat-linux-gnu-library/4.3/xml2’
* restoring previous ‘/home/R/x86_64-redhat-linux-gnu-library/4.3/xml2’

Any idea how to fix it? Thanks!

**Comment by tcairns-soundag** [comment]
If you try installing xml2 on its own do you get the same error? Just a quick `install.packages('xml2')`? I haven't run into this issue before and if it persists it might be worthwhile to reach out to the developers of the xml2 package to see if they have any suggestions!

**Comment by kwglam** [comment]
Yes, I have the same error when installing xml2. I will try to contact the xml2 developer and look for other solutions. Thanks!

**Comment by kwglam** [comment]
Hi,

I am now having the same issue as @BeatrizFaustino posted before. Any idea how to fix it?? Thanks!!

Downloading GitHub repo SoundAg/sounDMR@HEAD
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpwEPJyi/remotes327cf5a38f1e1/SoundAg-sounDMR-dbf6e22/DESCRIPTION’ ...
─  preparing ‘sounDMR’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sounDMR_2.2.2.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/gpfs/gsfs10/users/R/rhel8/4.3’
(as ‘lib’ is unspecified)
* installing *source* package ‘sounDMR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘data.table::melt’ by ‘reshape2::melt’ when loading ‘sounDMR’
Warning: replacing previous import ‘data.table::dcast’ by ‘reshape2::dcast’ when loading ‘sounDMR’
Warning: replacing previous import ‘changepoint::logLik’ by ‘stats::logLik’ when loading ‘sounDMR’
Warning: replacing previous import ‘changepoint::coef’ by ‘stats::coef’ when loading ‘sounDMR’
** help
*** installing help indices
  converting help for package ‘sounDMR’
    finding HTML links ... done
    add_changepoint_info                    html  
    add_zoom_coords                         html  
    boot_score                              html  
    changepoint_analysis                    html  
    create_cols_for_individuals             html  
    create_dmr_obj                          html  
    create_fixed_effects                    html  
    create_formula                          html  
    create_gene_percent_x                   html  
    create_methyl_summary                   html  
    create_random_effects                   html  
    find_DMR                                html  
    find_changepoint_col_options            html  
    find_cpt_mean                           html  
    generate_megaframe                      html  
    generate_methylframe                    html  
    generate_zoomframe                      html  
    get_standard_methyl_bed                 html  
    group_DMR                               html  
    individual_DMR                          html  
    pivot_and_subset                        html  
    plot_changepoints                       html  
    run_binomial                            html  
    run_model                               html  
    save_model_summary                      html  
    sound_score                             html  
    split_by_chromosome                     html  
    split_by_chunk                          html  
    subset_cols                             html  
    subset_methyl_summary                   html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Warning: replacing previous import ‘data.table::melt’ by ‘reshape2::melt’ when loading ‘sounDMR’
Warning: replacing previous import ‘data.table::dcast’ by ‘reshape2::dcast’ when loading ‘sounDMR’
Warning: replacing previous import ‘changepoint::logLik’ by ‘stats::logLik’ when loading ‘sounDMR’
Warning: replacing previous import ‘changepoint::coef’ by ‘stats::coef’ when loading ‘sounDMR’
Error: package or namespace load failed for ‘sounDMR’ in namespaceExport(ns, exports):
 undefined exports: plot_changepoints
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/gpfs/gsfs10/users/R/rhel8/4.3/sounDMR’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpwEPJyi/file327cf55870a941/sounDMR_2.2.2.tar.gz’ had non-zero exit status

**Comment by jcolicchio-soundag** [comment]
Hello @kwglam ,

Sorry you are having an issue with the install!  It looks the issue is related to the version of the namespace file that is being used for the export step with the SounDMR.R file that contains the actual functions.  This is in part due to us biting off a bit more than we could chew and will be remedied hopefully by mid January, but in the mean time, it should still be very possible to install and run the old version of the function.  However do note that this version is still in beta for whole genome work (that the january update will improve upon).  

You should have luck installing (I hope!) if you delete the downloaded files assouciated with sounDMR and then under the releases section on github, clicked on the most recent release, download the .tar.gz file and in Rstudio I hit install under packages and selected the downloaded file.

I hope this helps!

Best,
Jack

**Comment by kwglam** [comment]
Do you mean .tar.gz in this link https://github.com/SoundAg/sounDMR/files/13181805/sounDMR_2.2.2.tar.gz?

**Comment by kwglam** [comment]
> Do you mean .tar.gz in this link https://github.com/SoundAg/sounDMR/files/13181805/sounDMR_2.2.2.tar.gz?

Yes, got the library installed. Thanks very much for your help!!
